; This file was auto-generated by drush make
core = 7.x

api = 2

projects[] = drupal

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.

projects[malotor_profile][type] = "profile"
projects[malotor_profile][download][type] = git
projects[malotor_profile][download][branch] = "master"
projects[malotor_profile][download][url] = http://git.drupal.org/sandbox/malotor/2065789.git